# -*- coding: utf-8 -*-
"""日経225オプション損益シミュレーター

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1I5RyNVcZoe1QFi3plHP0MmSrfT0nyOJ7
"""

import streamlit as st
import pandas as pd
import numpy as np
import plotly.graph_objects as go

# -----------------------------------------------------------------------------
# 1. 計算ロジックの定義 (仕様書に基づくコア部分)
# -----------------------------------------------------------------------------
def calculate_option_pnl(entry_price, current_price, strike_price, premium, quantity, option_type, side, multiplier=1000):
    """
    オプション1枚あたりの損益を計算する関数

    Parameters:
    - current_price: 評価時の原資産価格（日経平均）
    - strike_price: 権利行使価格
    - premium: 取得単価（プレミアム）
    - quantity: 枚数
    - option_type: "Call" or "Put"
    - side: "Buy" (買い) or "Sell" (売り)
    - multiplier: 取引単位（ラージなら1000、ミニなら100。デフォルト1000）

    Returns:
    - 損益額 (円)
    """

    # 本質的価値（Intrinsic Value）の計算
    if option_type == "Call":
        # コール: MAX(原資産価格 - 権利行使価格, 0)
        intrinsic_value = max(current_price - strike_price, 0)
    else: # Put
        # プット: MAX(権利行使価格 - 原資産価格, 0)
        intrinsic_value = max(strike_price - current_price, 0)

    # 損益計算（仕様書の4パターンを再現）
    # 注: 実際の金額にするため multiplier を掛けています

    if side == "Buy":
        # 買い: (本質的価値 - プレミアム) * 枚数 * 単位
        pnl = (intrinsic_value - premium) * quantity * multiplier
    else: # Sell
        # 売り: (プレミアム - 本質的価値) * 枚数 * 単位
        pnl = (premium - intrinsic_value) * quantity * multiplier

    return pnl

# -----------------------------------------------------------------------------
# 2. アプリケーション設定
# -----------------------------------------------------------------------------
st.set_page_config(page_title="日経225 OP損益シミュレーター", layout="wide")

st.title("📊 日経225オプション 損益シミュレーター")
st.markdown("""
スプレッドシートのロジックを元にした損益計算アプリです。
左側のサイドバーでポジションを設定してください。
""")

# -----------------------------------------------------------------------------
# 3. サイドバー：ポジション入力エリア
# -----------------------------------------------------------------------------
st.sidebar.header("ポジション入力")

# 設定：取引単位（ラージ/ミニ）
unit_select = st.sidebar.radio("取引単位倍率", [1000, 100], format_func=lambda x: "x1000 (ラージ)" if x == 1000 else "x100 (ミニ)")

positions = []

# 第1組〜第5組までの入力フォームを作成
for i in range(1, 6):
    with st.sidebar.expander(f"第 {i} 組", expanded=(i==1)):
        c1, c2 = st.columns(2)
        with c1:
            o_type = st.selectbox(f"種別_{i}", ["Call", "Put"], key=f"type_{i}")
        with c2:
            side = st.selectbox(f"売買_{i}", ["Buy", "Sell"], key=f"side_{i}", format_func=lambda x: "買い" if x == "Buy" else "売り")

        strike = st.number_input(f"権利行使価格_{i}", min_value=0, value=38000 if i==1 else 0, step=125, key=f"strike_{i}")
        premium = st.number_input(f"プレミアム_{i}", min_value=0, value=0, step=5, key=f"prem_{i}")
        qty = st.number_input(f"枚数_{i}", min_value=0, value=0, key=f"qty_{i}")

        # 有効なポジション（枚数が1以上）のみリストに追加
        if qty > 0:
            positions.append({
                "group": f"第{i}組",
                "type": o_type,
                "side": side,
                "strike": strike,
                "premium": premium,
                "quantity": qty
            })

# 現在のポジション一覧表示（サイドバー下部）
if positions:
    st.sidebar.markdown("---")
    st.sidebar.subheader("入力中のポジション")
    df_pos = pd.DataFrame(positions)
    # 表示用にカラム名を日本語化
    display_df = df_pos.copy()
    display_df.columns = ["組", "種別", "売買", "権利価格", "価格", "枚数"]
    display_df["売買"] = display_df["売買"].map({"Buy": "買い", "Sell": "売り"})
    st.sidebar.dataframe(display_df, hide_index=True)
else:
    st.info("サイドバーでポジション（枚数1以上）を入力してください。")

# -----------------------------------------------------------------------------
# 4. メイン画面：シミュレーション設定
# -----------------------------------------------------------------------------

# シミュレーション範囲の設定
col_param1, col_param2, col_param3 = st.columns(3)
with col_param1:
    center_price = st.number_input("中心価格（現在値）", value=38000, step=100)
with col_param2:
    range_width = st.number_input("表示範囲（上下幅）", value=3000, step=500)
with col_param3:
    step_price = st.number_input("刻み値", value=125, step=125)

min_price = center_price - range_width
max_price = center_price + range_width
sim_prices = np.arange(min_price, max_price + step_price, step_price)

# -----------------------------------------------------------------------------
# 5. 計算実行
# -----------------------------------------------------------------------------

if positions:
    results = []

    for price in sim_prices:
        total_pnl = 0
        breakdown = {} # 各組ごとの損益

        for pos in positions:
            pnl = calculate_option_pnl(
                entry_price=0, # 今回の簡易計算ではエントリー時の原資産価格は不要
                current_price=price,
                strike_price=pos["strike"],
                premium=pos["premium"],
                quantity=pos["quantity"],
                option_type=pos["type"],
                side=pos["side"],
                multiplier=unit_select
            )
            total_pnl += pnl
            breakdown[pos["group"]] = pnl

        # 結果行を作成
        row = {"日経平均": price, "合計損益": total_pnl}
        row.update(breakdown)
        results.append(row)

    df_result = pd.DataFrame(results)

    # -----------------------------------------------------------------------------
    # 6. 可視化：損益グラフ
    # -----------------------------------------------------------------------------
    st.subheader("📈 損益シミュレーション・グラフ")

    fig = go.Figure()

    # 合計損益の線
    fig.add_trace(go.Scatter(
        x=df_result["日経平均"],
        y=df_result["合計損益"],
        mode='lines',
        name='合計損益',
        line=dict(color='blue', width=3),
        fill='tozeroy', # 0ラインまで塗りつぶし
        fillcolor='rgba(0, 0, 255, 0.1)' # 薄い青
    ))

    # 損益分岐点（0ライン）
    fig.add_hline(y=0, line_dash="dash", line_color="red")

    # レイアウト調整
    fig.update_layout(
        title="満期損益図 (Payoff Chart)",
        xaxis_title="日経平均株価",
        yaxis_title="損益 (円)",
        hovermode="x unified",
        height=500
    )

    st.plotly_chart(fig, use_container_width=True)

    # -----------------------------------------------------------------------------
    # 7. 可視化：損益早見表
    # -----------------------------------------------------------------------------
    st.subheader("📋 損益早見表")

    # データフレームのスタイリング
    # 損益がプラスなら青文字、マイナスなら赤文字にする関数
    def color_pnl(val):
        color = 'red' if val < 0 else 'blue'
        return f'color: {color}'

    # 数値フォーマット（カンマ区切り）
    st.dataframe(
        df_result.style
        .format("{:,.0f}") # カンマ区切り
        .map(color_pnl, subset=df_result.columns[1:]) # 日経平均カラム以外に色適用
        .highlight_between(left=0, right=0, axis=1, props="background-color: #ffffcc") # 0円に近いところをハイライト
    , use_container_width=True, height=400)

    # -----------------------------------------------------------------------------
    # 8. 統計情報
    # -----------------------------------------------------------------------------
    max_profit = df_result["合計損益"].max()
    max_loss = df_result["合計損益"].min()

    col_stat1, col_stat2 = st.columns(2)
    with col_stat1:
        st.metric("最大利益 (範囲内)", f"{max_profit:,.0f} 円")
    with col_stat2:
        st.metric("最大損失 (範囲内)", f"{max_loss:,.0f} 円")

else:
    # ポジションがない場合のプレースホルダー
    st.warning("👈 左のサイドバーからポジションを追加してください。")
    st.write("例：コール買い 38000円 プレミアム300円 1枚 など")